version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: "08:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
