name: Changesets

on:
  # main ブランチ への push があった場合実行
  push:
    branches:
      - main

permissions:
  id-token: write  # OIDCに必要
  contents: write      # リポジトリへのpush権限
  pull-requests: write # PR作成権限

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - run: corepack enable 
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install dependencies
        run: pnpm install
      - name: Create release PR or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
